const termsContent = [
  { "content": "Unless otherwise explicitly agreed in writing these General Terms and Conditions shall apply to all agreements, contracts, orders, sales and deliveries of Goods or services by the Seller.", },
  {
    "content": "The Buyer may not transfer its rights and obligations without the prior written consent of the Seller, which shall not be unreasonably withheld. ",
    "sublist": [
      "Throughout this document the following definitions shall be applied and referred to:"
    ]
  },
  { "content": "“Seller’’ means SINGAPORE MARINE ENGINEEING AND SPARES PTE LTD, or any affiliated companies appointed or named in the agreement, the Order Confirmation, or any other communication between the Parties." },
  { "content": "‘Buyer’’ means any party requesting quotations, placing orders, purchasing, or otherwise receiving Goods or services from the Seller, including but not limited to the Vessel and her owners, charterers, operators, managers, masters, agents, and brokers. Any affiliate of the Buyer, or companies owning vessels, which takes delivery of Goods and/or consumes Goods or otherwise participates in or benefits from sales or services encompassed by this agreement shall be deemed party to this agreement and shall be jointly liable with the Buyer for all obligations pursuant to this agreement in respect of such supplies. The Buyer undertakes to procure that such owners and affiliate(s) undertake(s) liability on the terms of this agreement jointly with the Buyer and the Buyer declares that it has authority to act on behalf of such owners and affiliate(s)." },
  { "content": "“Parties” means the Buyer and the Seller together. " },
  { "content": "“Terms” means these General Terms and Conditions." },
  { "content": "‘’Vessel’’ means the ship, barge or on- or off-shore facility or any other type of vessel no matter character that receives the Goods, either as end-user or as transfer unit to a third party." },
  { "content": "“Goods & Services” means all items ordered by the Buyer or supplied by the Seller, including but not limited to ship stores, accessories, provisions and equipment and any related services provided by the Seller. " },
  { "content": "“Order Confirmation” means a written confirmation by Seller of an order placed by the Buyer and/or confirmation of an agreement otherwise by the Seller." },
  { "content": "“End-user” means the party ultimately disposing of, using, or consuming the Goods, including the Vessel and her owners, charterers, operators, managers, deponent owners, agents, and brokers. " },
  { "content": "“Sanctions laws” means any sanction, prohibition or restriction imposed by the UN, the EU, the UK, the USA, including but not limited to the US Department of the Treasury Office of Foreign Asset Control (“OFAC”) including the OFAC Specially Designated Nationals or Blocked Persons List (SDN) and the US Department of State, or any other country or international body." },
  { "content": "PRICES The Seller’s prices are based on the price level of the Goods and all other costs and charges, hereunder taxes and duties known at the time of concluding the agreement. Any price increase on goods, or additional costs borne by the Seller whatsoever, caused by any change in the Seller’s contemplated source of supply or otherwise, occurring after the agreement has been concluded, shall be added to the agreed sales price of the Goods or the services provided by the Seller. The Seller shall give the Buyer prior notice of such increases in the agreed sales price within a reasonable time after the Seller becomes aware of the relevant circumstances.", },
  {
    "content": "All prices and/or tariffs are exclusive of GST, sales taxes, export, or import taxes, dues, quay dues, and other duties and taxes of any kind, which shall be for the account of the Buyer.",
    "sublist": [
      "Seller have a right to cancel his quoted price at any time due to no availability, long delivery time, wrong price, Typo or Computer error.",
      "Seller have a right to provide quotes for the item Oem, Reliable, Copy, Genuine product price. Buyer had accepted the price according to the Quote he doesn’t have right to Cancel the Purchase order upon confirmation.",
      "Seller have a right to impose 50% Cancellation charges on the Buyer if a actual PO is sent via Email/ Fax/ Physical copy. Buyer cannot cancel the PO",
    ]
  },
  { "content": "Any and all orders are subject to an Order Confirmation by the Seller before such order is binding on the Seller. All orders are binding on the Buyer and cannot be cancelled by the Buyer after the Order Confirmation is sent. " },
  { "content": "In all cases the Order Confirmation shall be the valid documentation for qualities and quantities ordered as well as for other terms agreed. It is the Buyer’s sole responsibility to check and address any discrepancies between the Order Confirmation and the Buyer’s order, and the Seller shall not be held liable for such discrepancies. " },
  { "content": "Any master, officer or crew member at the Vessel or agent/representative of the Buyer shall be deemed authorised by the Buyer to receive and inspect the Goods and confirm that the Goods are in accordance with the accompanying delivery note. " },
  { "content": "Confirmation that the goods are in accordance with the accompanying delivery note shall be deemed given and the goods deemed examined and accepted in every respect by the Buyer by taking delivery of the Goods, notwithstanding reservations or conditions added to the delivery note by the Buyer at the time of delivery. " },
  { "content": "In consideration of essentiality of time of delivery and in the interest of provisioning the Vessel, if Goods are not reasonably obtainable for delivery for whatever cause or reason, Wrist reserves the right to substitute such Goods, with similar alternative Goods. Substitution will not increase the price per unit of measure but may increase the total price if the corresponding units increases." },
  { "content": "All sales are final and cannot be cancelled by the Buyer after the Order Confirmation is sent. Return of Goods are subject to acceptance by the Seller and may be subjected to a deduction in the refunded purchase amount in the Sellers discretion. " },
  { "content": "If, for whatever reason, the quantity or quality agreed is not available for delivery by reasonable means, the Seller cannot be held liable for not supplying the Goods or services in accordance with the Order Confirmation. In such situations the Seller shall give the Buyer notice within reasonable time after the Seller becomes aware hereof. The Seller shall initiate discussions with the Buyer on how to mitigate shortcomings in quantity by supplying the missing quantities at a convenient port/place suitable for both parties. " },
  { "content": "Any and all claims relating to a delivery shall be notified in writing to the Seller no later than 3 calendar days after delivery or in case of nondelivered 3 calendar days after the anticipated delivery time unless the reasons for the claim could not be detected after thorough examination at the time of delivery in which case the claim must be notified in writing to the Seller no later than 10 calendar days after delivery. If the Buyer rejects to receive a delivery at the time of delivery due to quantity or quality concerns the Buyer must immediately notify the Seller of the rejection. Claims and/or rejections notified later shall be deemed time barred and fully waived by the Buyer. " },
  {
    "content": "If a claim and/or rejection relates to quantity or quality the claim shall be accompanied by photos showing the non- conformity and the original packaging with batch numbers and include a written report detailing the reasons for the claim and/or rejection. The Buyer must return the claimed Goods or provide additional documentation as requested from time to time by the Seller.",
    "sublist": [
      "Warranty depends on the Factory / Maker seller will be not responsible for the Quality of the product.",
    ]
  },
  { "content": "If a valid claim exists, one of the following remedies shall apply in the sole discretion of the Seller: 1) a refund of the purchase price of the non-conforming Goods; 2) repair of the non-conforming Goods; or 3) redelivery of the non-conforming Goods. " },
  { "content": "The Seller’s total liability towards the Buyer under any one Order Confirmation shall always be limited to an amount equal to the stated price of the Goods or services in such Order Confirmation and in any case (and if no order is linked to the claim) the total liability is maximum the aggregated value of products and services delivered in the month in which the incident causing the claim occurred. This applies irrespective of whether the Seller’s liability arises out of the delivery of non-conforming Goods, quantities, product liability, delays, or acts or omissions committed by the Seller or the Seller’s representative. Seller has no liability for any goods containing hazardous material, chemical substances and the like and will have no liability in connection with any supplier declarations of such. " },
  { "content": "The Seller cannot be held liable for any type of consequential damages or indirect losses hereunder but not limited to any loss of profit, loss of use, loss of revenue, loss of contracts, loss of business, loss of goodwill, increased costs and expenses, lay-time, demurrage or wasted expenditure. The Seller, the Seller’s representative, driver, or any person representing the Seller shall in no event be held responsible or liable for any delay. " },
  { "content": "The Seller cannot be held liable for non-performance due to an event of force majeure which shall mean any cause of events beyond the reasonable control of the Seller, hereunder but not limited to unavailability of Goods from the sources of supply of the Seller, lack of reasonable means of transportation, cyberattacks, hacking of IT systems and the like, and acts of God." },
  {
    "content": "Limitations of liabilities in these Terms shall apply equally to the delivery of Goods and services hereunder but not limited to storage and/or transportation services, freight forwarding, custodian and/or carrier services. ",
    "sublist": [
      "Seller will be not responsible for missing of items, damage of items if the buyer engaged 3rd party to collect and deliver the orders."
    ],
  },
  { "content": "Any delivery time agreed shall be regarded as a best estimate and as an approximate delivery time." },
  { "content": "In all cases the Buyer must give not less than 72 hours of notice to the Seller of approximate delivery time, followed by 48 and 24 hours of notice, where last notice must be final and exact. " },
  { "content": "The Seller may in its own discretion deliver the Goods of a single Order Confirmation in one or more lot(s). " },
  { "content": "The Buyer warrants and ensures that any government permits or approvals necessary for the export of the Goods has been obtained. " },
  { "content": "Delivery is deemed to have taken place at the earliest of: when the Goods are placed (a) alongside the Vessel at the named port of delivery, or (INCOTERMS© FAS) (b) alongside the barge or other vessel carrying the Goods to the Vessel, or (c) placed at the Buyer’s disposal. The Buyer must bear all, and any costs related to the Goods and transportation thereof after delivery, hereunder but not limited to costs of cranes and barge delivery and the Buyer will bear the risks of loss of or damage to the Goods occurring after delivery. All risks insurance for such barge/vehicle transport shall be made by and for the account of the Buyer, including the risk for goods carried on deck. F.6 If storage of Goods is arranged by the Seller on request of the Buyer the risk shall pass at the time the Goods are placed in storage. Transportation from the place of storage shall be for the risk and account of the Buyer. " },
  { "content": "If delivery is required outside normal working hours of the operation performing the delivery or on a Saturday, Sunday or religious, national, or legal holiday the expenses incidental to delivery at such time shall be reimbursed by the Buyer. " },
  { "content": "Payment shall be made by the Buyer no later than on the due date stated in the invoice." },
  { "content": "Payment shall, unless otherwise agreed in writing, be made in the currency stated on the invoice, and all payments are to be made free of bank charges and other costs. " },
  { "content": "Payment shall be made to the Seller’s nominated bank account as stated on the invoice or in cash if no credit has been agreed. " },
  { "content": "Payment shall be made in full, without any set-off, deduction and/or discount, unless agreed in writing prior to payment being made." },
  { "content": "In the event that payment is not received by the Seller by the due date the Seller is entitled to interests at the rate of 3 percent per month pro rata without prejudice to any other rights or remedies available to the Seller. " },
  { "content": "All costs and expenses incurred by the Seller in connection with the collection of any overdue payments, including but not limited to interest charges, internal costs, expenses to lawyers and debt collectors, court fees, etc, shall be indemnified by the Buyer upon demand from the Seller. " },
  { "content": "All payments received by the Seller shall be applied first to settle interest as set out in clause, then to costs as set out in clause and then to the principal amount. " },
  { "content": "Notwithstanding any agreement to the contrary, all amounts owed to the Seller will be due and payable immediately in case of bankruptcy, insolvency, moratorium, reorganization, or other situations of the Buyer which affect the Seller’s rights generally or which in the sole opinion of the Seller adversely affects the financial position of the Buyer. " },
  { "content": "The Seller shall always be entitled to require that the Buyer provides security for the proper performance of all its payment obligations to the Seller in such manner as shall be deemed sufficient by the Seller. Failure to immediately provide such security shall entitle the Seller, inter alia, to suspend further performance of all orders. " },
  { "content": "In case of any default in payment by the Buyer, any rebate or discount awarded by the Seller to the Buyer shall become non- applicable and the Seller may charge the full price for the Goods. " },
  { "content": "In situations where the Seller has agreed to store and transport items or goods on behalf of the Buyer (such items are referred to as ‘’Owner’s Goods’’), the sole risk of the Owner’s Goods while the goods are in the custody of the Seller, or third parties acting on the Seller’s behalf, remains with the Buyer." },
  { "content": "Storage and transportation of Owner’s Goods are provided to the Buyer by the Seller only based on prior agreement on each occasion between the parties. " },
  { "content": "Owner’s Goods are considered as received for transport and/or storage only. The Seller has accepted to carry such goods to the receiving Vessel on the condition that the Seller cannot be held liable for any loss, damage or delay to the said goods (in whole or in part) occurring during offloading, storage, loading and transportation arising including but not limited to negligence on the part of the Seller or subcontractors / representatives, and the Buyer shall indemnify the Seller from any loss and/or liability arising out of the performance of the services related to the Owner’s Goods. " },
  { "content": "The Buyer acknowledges and accepts that barge transport may be performed as deck cargo, and the Buyer shall have the sole responsibility of proper and sufficient packaging of the Owner’s Goods. " },
  { "content": "The Seller shall be deemed to have no knowledge of the weight, contents, or quality of the Owner’s Goods and in no way whatsoever can the Seller be held responsible for same." },
  { "content": "With reference to Article above it remains the sole responsibility of the Buyer to ensure and the Buyer warrants that Owner’s Goods are stored, transported, exported, and imported in accordance with all applicable laws and regulations. The Buyer shall indemnify the Seller all costs borne by the Seller related to the storage, transport, export and/or import of the Owners Goods if such are due to issues of compliance with laws and regulations, or due to health and safety measures taken by the Seller to protect staff or property belonging to the Seller or third parties." },
  { "content": "The Buyer shall ensure that proper insurance is covering the Owners Goods during the period of transport and storage by the Seller or its representatives. " },
  { "content": "The Buyer warrants that all Owners Goods provided for logistics and storage services shall not be dangerous, illegal, or dual use in nature. The Buyer agrees to comply with all applicable laws, regulations, and safety standards regarding the handling, transportation, and storage of Owners Goods. If any breach of this warranty occurs, the Buyer shall indemnify and hold the Seller harmless from any losses or damages arising from the breach of this warranty. " },
  { "content": "The Seller’s liability for carriage or storage of the Buyer’s Goods shall always be limited in accordance with the clauses in article. " },
  { "content": "The Buyer hereby acknowledges and accepts that the Seller may capture photographs of the Buyer's vessel, both inside and outside, as well as photographs including the Seller's employees, during on-site delivery of goods or services, for marketing purposes, including but not limited to social media." },
  { "content": "The Seller warrants on-site compliance with applicable data protection rules and regulations. Both parties acknowledge that they individually act as data controllers and agree to uphold their respective obligations under the applicable data protection rules and regulations" },
  { "content": "The Buyer warrants that (i) the Buyer and the End-User is not in breach of any Sanctions Laws; (ii) that the Buyer is purchasing the Products as principal and not as agent, trustee or nominee of any person or company with whom transactions are prohibited or restricted under any Sanctions Laws; (iii) the Vessel is not and will not be employed, chartered or controlled by any person or company, or transport any cargo, contrary to the restrictions or prohibitions under any Sanctions Laws; (iv) the Buyer, the Vessel, or the End-User will not use or otherwise employ the Goods or the Vessel for any purpose contrary to the restrictions or prohibitions under any Sanctions Laws. " },
  { "content": "The Buyer acknowledges that its conduct is subject to certain anticorruption and anti-bribery laws and regulations. Therefore, the Buyer shall comply with all such applicable laws and regulations and agrees not to offer, promise, pay or authorize the payment of any money or anything of value, or take any action in furtherance 4 of such a payment, whether by direct or indirect means, to any public official or private individual to influence the decision of such person in the performance of any duties. " },
  { "content": "It is of highest importance to the Seller not to engage in any activity which might be in breach of any Sanctions Laws or any anti-corruption and anti-bribery laws and regulations, and the Buyer is obliged to immediately notify the Seller of any risk of such breach. If the Seller, in its sole discretion, believes that a breach of clause. Has occurred the Seller is released from all obligations under any agreement with no compensation owed to the Buyer, and the Buyer shall be fully liable to the Seller for all losses, claims, costs, and expenses suffered as a consequence of such breach." },
  { "content": "If the company to whom the Order Confirmation is issued is not the registered owner of the Vessel, the master or any other officer or representative of the Vessel by signing or stamping the delivery notes or other similar document shall be deemed to have full authority on behalf of the Vessel and her owners to accept these Terms." },
  { "content": "If the company to whom the Order Confirmation is issued is not the registered owner of the Vessel, the master or any other officer or representative of the Vessel by signing or stamping the delivery notes or other similar document shall be deemed to have full authority on behalf of the Vessel and her owners to accept these Terms." },
  { "content": "These Terms, and all Order Confirmations, agreements and / or transactions to which these Terms apply, shall be governed by and construed in accordance with Danish substantive law. CISG does not apply. " },
  { "content": "The Contract shall be governed by the laws of Singapore." },
  { "content": 'Any dispute arising out of or in connection with any Contract, including any question regarding its existence, validity, or termination, shall be referred to and finally resolved by arbitration in Singapore in accordance with the Arbitration Rules of the Singapore International Arbitration Centre ("SIAC Rules") for the time being in force, which rules are deemed to be incorporated by reference in this clause. The Tribunal shall consist of a single arbitrator to be appointed by the Chairman of the SIAC. The language of the arbitration shall be English. The award of the arbitrator shall be final and binding upon the parties.' },
]

export default termsContent;