export const getList = (id) => {
  const list = [
    {
      text: [
        "On Voyage Repairs.",
        "Main engine overhauls at Anchorage.",
        "Auxiliary engine crankshaft renewal.",
        "Steering gear fault finding.",
        "Turbocharger service and overhaul.",
        "Installation and commissioning of hydraulic power pack.",
        "Boiler repair and overhaul.",
        "Alongside/Safe Berth Repairs.",
        "Anchorage Repairs.",
        "Complete or Partial Engine Overhaul.",
        "Routine maintenance, troubleshooting and repair of engines.",
        "Technical Consulting Service.",
        "Service of fuel systems of all 2 and 4 Stroke Engine Systems.",
        "Reconditioning of Fuel Pumps (Single / Inline).",
        "Reconditioning of Plungers and Barrels.",
        "Reconditioning of Fuel Valves and Injectors.",
        "Repair and overhaul Main Engine medium and high speed diesel engines.",
        "Repair and overhaul of hydraulic clutches and transmission gears.",
        "Repair and overhaul of engine room and deck machineries, pumps, air compressors, windlass.",
        "Workshop fabrication, reconditioning, restoration of machinery components to maker’s standard.",
        "Repairs, modification and installation of electrical equipment.",
        "Repair and rewinding of electric motors and alternators.",
        "Renewal and fabrication of engine room deck and double bottom tanks pipes & fittings.",
        "Tank cleaning.",
        "We provide piping services such as pipeline structure fabrication and installation for pipes system in Engine, Pump rooms.",
        "We offer wide range of services for afloat steel repairs and fabrication.",
      ],
    },
    {
      text: [
        "Supply new Shipbuilding and Conversions of Ship Air-Condition/Refrigeration.",
        "Supply all kinds of Air-Condition/Refrigeration Compressor(on exchange basis).",
        "Supply all kinds of Air-Condition/Refrigeration Compressor Replacement Spare Parts.",
        "Supply Marine Air-Conditioning Wall-Split Unit/Portable Spot Cooler.",
        "Repair all kinds of Air-Condition/Refrigeration Compressor.",
        "Rewind all kinds of Motors AC/DC.",
        "Fabrication of all kinds of Evaporator Coil, Condensers, Chill Water Coil Steam Heating Coils, Chiller Coils, Oil Cooling Coilsand Retubing etc.",
        "Anchorage repair and Voyage Repair.",
        "We can supply compressor on exchange basis.",
        "24hr hotline for technical troubleshooting and related spares parts procurement.",
      ],
    },
    {
      text: [
        "Provisions - Such as eatables: Vegetable, Meat, Dairy products, etc.",
        "Galley utensils.",
        "Rope - Steel wire, Mooring rope, Wire rope, etc.",
        "Marine Paint & Equipments - Clearing gun, Air duster, Paint spray guns, All marine paint, etc.",
        "Safety equipments & Protective gear - Fire Extinguisher, Gas Detectors, Life Jackets, Safety Mask, Smoke Detectors, SOLAS Publication, Liferaft, Lifeboat & accessories, etc.",
        "Nautical equipments - Charts, Marine radio, Navigation instruments, Merchant flags, etc.",
        "Medicine - Equipment, Medical chests, Medical supplies, etc.",
        "Stationery - Calculators, Computer & Accessories, Stamps, Files, Paper, etc.",
        "Hardware - Racks, Holders, Locks, Cabinet hardware, Bathroom hardware, etc.",
        "Hand, Cutting, Electric & Mechanical tools - Ladders, Cutters, Drillers, Cables, Lamps, Battery, Cargo lights, etc.",
        "Valves & Pipes - Ball, Butterfly, Gate, Check, Globe valves, Aluminium, Steel, PVC pipes, etc.",
        "Welding equipment - Electrodes, Rods, Gas Cylinders, Hoses, Gauges, etc.",
      ],
    },
    {
      text: [
        "Our team provides manning & crew management, offering our customers high quality, cost-efficient, and personalized crewing services. These services support and encourage safe and efficient ship operation while promoting clients’ competitiveness.",
        "We provide a quality service where our customers have total confidence in our ability to manage the human resources on their behalf. This gives them the freedom to concentrate on other aspects of ship operation, management, and ownership.",
        "We offer various crew management combinations, tailored specifically to your needs.",
        "We can either provide select crew members or supply a full crew complement. When supplying a full crew, we take full responsibility for them. Our crew roster includes highly-qualified, experienced members for all types of vessels, from Skippers to assistants.",
        "Despite our extensive crew offerings, we maintain the benefits of a highly experienced and well-trained crew. Upon request, we can manage responsibilities such as visas, medicals, crew travel, and payroll.",
        "We are highly flexible, adjusting to provide whatever level of support you require.",
      ],
    },
    {
      text: [
        "For Purchasing:",
        "· Spares usage and inventory.",
        "· Spares future prediction.",
        "· Stores supply and inventory.",
        "· Automatic requisition generator.",

        "For Technical:",
        "· Docking and repair planning.",
        "· Survey status & job reports.",
        "· Integrated maintenance and class survey.",
        "· Condition based maintenance.",
        "· Alert and notifications.",

        "For Finance:",
        "· Budget control.",
        "· History of supply.",
        "· Invoice connecting with the supply.",
        "· Overdue alert.",

        "For Vessel:",
        "· Spares requisition.",
        "· Planning.",
        "· Rescheduling.",
        "· Follow up for stores/ repairs/ spares.",
        "· Reporting to Shore based office.",

        "Our software allows all labels, messages, and instructions to be configured as per the client's request. Additional languages can be added to aid the workflow and minimize human activities across all departments, thereby improving efficiency.",
      ],
    },
  ];
  return list[id - 1];
};
